#%RAML 1.0 NamedExample
value:
   Name: "Ritu"
   OrderDate: 2020-12-23T17:35:00
   MobileNo: 1234567890
   Address:
      street: "Nagar Road"
      city: "Pune"
      zipcode: 411006
   Products:
      Product1: "Fridge"
      Price1: 24532
      Product2: "Washing Machine"
      Price2: 74653
      Product3: "T.V."
      Price3: 14352
  